### ISSUE TITLE
TODO: Sprint 1

### ISSUE THREAD

**Issue by mtwichan** [echooo-labs/echooo-app#22]
A quick and dirty TODO list for our first sprint.

TODO for @Aryaan082:
## Frontend
- [ ] refactor `MessagingPage.js` so that the page header and left column containing the wallet addresses are their own component. Ideally, the messaging page component is pretty much the global entry point for the state hooks
- [ ] reduce the number of props being passed into the components. for example, modal hooks are used a ton. I wonder if you could use something like `useReducer` or create a custom hook to manage the modal state?
- [ ] move landing page and messaging page into their own page component in the `pages` folder 
- [ ] NFT to NFT swapping selection & message
- [ ] NFT to token swapping selection & message
- [ ] token to user selection & message
- [ ] https://github.com/echooo-labs/echooo-app/issues/16 -> persist selected end receiever address or find alternative solution
- [ ] Better UI/UX for sending message loading indicator

## Backend
- [ ] Sending messages to an address that hasn't created a communication key pair is not supported ** important one to solve
- [ ] If receiver changes communication key, this will clear messages for the sender as well, should we fetch all communication keys and decrypt messages for a historical message view? Currently the code queries the most recent communication key and decrypts messages based on that

TODO for @mtwichan 
## Frontend
- [ ] frontend optimizations `useCallback`, `useMemo` and `useEffect` demount
- [ ] frontend optimizations debounce & throttle

## Backend
- [ ] protect against graphQL injection for graphQL queries
- [ ] websockets integration with Alchemy and connect to messaging

## Misc
- [ ] README
